[tool.black]
line-length = 100
target-version = ["py312"]
exclude = [
  "venv",
  "migrations",
]

[tool.isort]
profile = "black"
line_length = 100
skip = ["venv", "migrations"]
known_first_party = ["accounts", "payments", "processing", "bots", "demo", "blog", "core"]

[tool.coverage.run]
branch = true
source = [
  "accounts",
  "payments",
  "processing",
  "bots",
  "demo",
  "blog",
  "core",
]
omit = [
  "*/migrations/*",
  "*/venv/*",
  "core/asgi.py",
  "core/wsgi.py",
  "manage.py",
]

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 70
