# Generated by Django 5.2.5 on 2025-10-04 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Button Click'), ('form_submit', 'Form Submission'), ('payment', 'Payment Initiated'), ('signup', 'User Signup'), ('login', 'User Login'), ('download', 'File Download'), ('other', 'Other')], db_index=True, max_length=50)),
                ('event_name', models.CharField(max_length=200)),
                ('event_data', models.JSONField(blank=True, null=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('page_url', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='analytics_e_event_t_676ab6_idx'), models.Index(fields=['session_key', 'timestamp'], name='analytics_e_session_1b3181_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('device', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('referrer_domain', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_on_page', models.IntegerField(blank=True, help_text='Seconds spent on page', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'path'], name='analytics_p_timesta_cd14c8_idx'), models.Index(fields=['session_key', 'timestamp'], name='analytics_p_session_982099_idx'), models.Index(fields=['ip_address', 'timestamp'], name='analytics_p_ip_addr_f9d0af_idx')],
            },
        ),
    ]
