# Generated by Django 5.2.5 on 2025-10-05 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pageview',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='pageview',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['country', 'timestamp'], name='analytics_p_country_7b28c5_idx'),
        ),
    ]
