# Generated by Django 5.2.5 on 2025-10-07 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_pageview_city_pageview_country_pageview_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('bot_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_b_timesta_edb034_idx'), models.Index(fields=['bot_type', 'timestamp'], name='analytics_b_bot_typ_24731b_idx')],
            },
        ),
    ]
